mysql:
  type: mysql
  host: 
  port: 3306
  username: 
  password: 
  database: demo
  synchronize: false
  timezone: Z
  logging: false

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456

logger:
  console: true
