mysql:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: shop
  synchronize: false
  timezone: Z
  logging: true


redis:
  host: 127.0.0.1
  port: 6379
  password: 123456

uploadDir: images

logger:
  console: true
